### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Skquark** [AndreHaueisen/flushbar#1]
I was excited to start integrating the FlushBar into my app a few months ago, but got a build error as soon as I add it to my yaml file, so I put it off.  Tried again with the new version but got the same error, which is this:

The current Dart SDK version is 2.0.0-dev.61.0.flutter-c95617b19c.
Because [my app name] depends on flushbar >=0.2.6 which requires SDK version >=2.0.0-dev.52.0 <=2.0.0-dev.58.0.flutter-f981f09760, version solving failed.
pub get failed (1)
exit code 1

I also noticed it's listed as Unidentified in the dartlang packages directory now and I couldn't search for it directly anymore.  Thought you might want to know, but maybe that's because it's not working.  Dunno, but hope I can get it working.  Thanks.

**Comment by AndreHaueisen** [comment]
@Skquark , hi. I recommend that you wait for version 0.9 and above. I intend to release a breaking update that will make it easier to use. You won't need a Stack and won't need to carry a reference through the whole app anymore. I'm still figuring out how to do it, but I know it is possible.
About the error, did you run `flutter upgrade`? I will take a look and see if the problem is on my side, but I'm using Flushbar in my app normally.
Please, paste your `flutter doctor` when you get the chance.

**Comment by Skquark** [comment]
Thanks, no problem waiting for the next release, I can work around it.  Doesn't sound easy to have the component on top of the whole app rather than a stack widget overlay, good luck with that.
I definitely do the flutter upgrade like every day.  I'm thinking it might be because I'm on the dev channel and it's not recognizing the way the version is written out when resolving the comparison.  Here's my flutter doctor results:
 Flutter 0.5.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 020e0ef55c (3 weeks ago) • 2018-06-14 13:17:08 -0700
Engine • revision c3976b3c71
Tools • Dart 2.0.0-dev.61.0.flutter-c95617b19c

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.5.5, on Microsoft Windows [Version 10.0.17134.112], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.24.1)
[√] Connected devices (1 available)

**Comment by AndreHaueisen** [comment]
@Skquark ,  version 0.5.6 should solve the dependency issue. Thanks for reporting.

**Comment by Skquark** [comment]
Excellent, it's working now.. I'm ready to start integrating it in, I was getting bored of the standard OS toast notifications we were being forced to use without being able to customize.

A feature request I'd like to make, so I can do what I really wanted to do with this: Have a generic child widget container which overrides the whole title and message area so we could use the framework to put in anything we want in the flushbar.  I'd want to put a flexible height column in there to display a whole form, even with a SingleChildScrollView inside, then the button to Submit.. Maybe there's already a way to do this with what you have, and I just haven't played with it enough.  I'm just tired of using the standard Flutter ShowDialog-SimpleDialog which wasn't customizable enough for what I was trying to use it for.  I think this component is gonna make my interface look so much cooler without that much extra effort.  Thanks, keep up the good work, appreciated.
