### ISSUE TITLE
Show Flushbar with NavigatorState (GlobalKey)

### ISSUE THREAD

**Issue by fstof** [AndreHaueisen/flushbar#103]
In referral to [this](https://github.com/AndreHaueisen/flushbar/issues/79) issue 

If I may revive it. (its closed so I guess I'm trying a new one)

On `MaterialApp` you can provide a `GlobalKey<NavigatorState>` to the `navigatorKey` property. This serves as the root `Navigator` for the app
Many people (including me) use this `NavigatorState` to do navigation.

So what I have is a "NotificationService" that wraps `Flushbar`. This service gets initialised (with BuildContext) before `MaterialApp` so now the `context` in the `NotificationService` does not contain a `Navigator` and thus showing the Flushbar fails.

By providing an overloaded `show` function this could be remedied.
something like this
```dart
Future<T> show(GlobalKey<NavigatorState> navigatorKey) async {
    _flushbarRoute = route.showFlushbar<T>(
      // context: ????
      flushbar: this,
    );

    return await navigatorKey.currentState.push(_flushbarRoute);
}
```

**Comment by cwe1ss** [comment]
It seams like calling `Flushbar().show(navigatorKey.currentState.overlay.context)` does the trick!

Found here: https://stackoverflow.com/a/53350682/5214796

**Comment by fstof** [comment]
Thanks @cwe1ss 
That indeed does work
