### ISSUE TITLE
FEATURE: Set Text Color

### ISSUE THREAD

**Issue by rayliverified** [AndreHaueisen/flushbar#105]
**Describe the feature**
Add widget options to customize text color. Due to the text color being hardcoded as White, the toast background color cannot be a light color or the text is not readable.

**Paste relevant code**
![MaxthonSnap20200116155717](https://user-images.githubusercontent.com/19896174/72566248-169fef80-3879-11ea-87d1-0d3dd18311b3.png)

Please let me know if this library is still maintained. If so, I can submit a PR with the proposed feature. Thanks!

**Comment by rayliverified** [comment]
![MaxthonSnap20200116155944](https://user-images.githubusercontent.com/19896174/72566320-3a633580-3879-11ea-9fb7-ddc8779ba1b1.png)

**Comment by timopruesse** [comment]
You can use `messageText` and style the `Text` element to your needs.

**Comment by rayliverified** [comment]
Let me give that a try, thank you

**Comment by rayliverified** [comment]
@Chroma91 Your suggestion worked! Going to close this ticket as the functionality is present, if not easily accessible. 

In a future version, perhaps the API can be streamline.
