### ISSUE TITLE
spamming flushbar issues

### ISSUE THREAD

**Issue by Kucingemas** [AndreHaueisen/flushbar#11]
Hello, first of all, i'm sorry for my bad English and knowledge in the field, i'm new in this thing :)

Here are some things i found when i try to implement flushbar in my app
1. when i spam the button that trigger the flushbar, some of it got stuck in screen and i have to swipe it to dismiss it.
2. Sometimes, the last flushbar dismissed itself by disappearing into the bottom of the screen, and it also pulling my app to the bottom of the screen, leaving blank space on top of my screen and i cant scroll the app back to the top

**Relevant Code**

signIn(String email, String password, BuildContext context) async {
    this
        ._auth
        .signInWithEmailAndPassword(email: email, password: password)
        .then((user) async {
      //settingemail to shared preferences to pass into other screens
      sharedPreferences = await SharedPreferences.getInstance();
      sharedPreferences.setString("useremail", user.email);
      sharedPreferences.commit();

      Navigator.of(context).pop();
      Navigator.of(context).pushReplacementNamed("/joblist");
    }).catchError((e) {
      Flushbar()
        ..message = "error message"
        ..icon = Icon(
          Icons.info_outline,
          color: Colors.red,
        )
        ..duration = Duration(seconds: 3)
        ..leftBarIndicatorColor = Colors.red
        ..show(context);
    });
  }

**//**
Thankyou.

![screenshot_20180919-094327 1](https://user-images.githubusercontent.com/33223804/45728476-5bb70180-bbf2-11e8-86e7-a90589f904aa.png)

**Comment by AndreHaueisen** [comment]
Hi @Kucingemas 
I will investigate this behavior.
For now, there are ways you can be sure your user will not spam it by attaching a listener to know when it is showing.
Flushbar works by pushing a new route every time you call `show()`. Make sure you do not push a new route until Flushbar is dismissed. You can do that by attaching a listener to it or by using the `Future` yield by `dismiss()`

**Comment by Kucingemas** [comment]
thank you for your response and the alternative solution :)

**Comment by AndreHaueisen** [comment]
@Kucingemas ,
about your first issue. Make sure you follow the recommendations described in the `IMPORTANT` section of the [README file](https://github.com/AndreHaueisen/flushbar)

About your second issue, I believe it is fixed in version 9.1.

If you get the chance, try it out. Thanks for the feedback.

**Comment by Kucingemas** [comment]
@AndreHaueisen thank you for the updates, it worked well! 

edit:
the screen is still pulling down, i guess its because of the isDismissed(), this happened when i try to use isDismissed(). when i use the flushbar normally, it worked fine

**Comment by AndreHaueisen** [comment]
@XiaoHZhuaWaWa 
paste your code here

**Comment by XiaoHZhuaWaWa** [comment]
Flushbar()
          ..message = args[0]
          ..duration = Duration(seconds: 3)
          ..show(context);

**Comment by AndreHaueisen** [comment]
Are you following this [guideline](https://github.com/AndreHaueisen/flushbar#important)?

**Comment by XiaoHZhuaWaWa** [comment]
Yes, flushbar 0.9.1

**Comment by AndreHaueisen** [comment]
Paste the whole class. Not just the Flushbar code

**Comment by XiaoHZhuaWaWa** [comment]
No, it's no use. You can try clicking the button popup twice in a row

**Comment by AndreHaueisen** [comment]
Can not help you then. I'm using it in my app and it is working fine. There is a bug in your code and I'm trying to help you find it.

**Comment by AndreHaueisen** [comment]
@Kucingemas 
Paste your entire class here, please. Let me have a better idea of what is going on. I need to see if I can reproduce it.
A link to your class on Github would work fine too.

**Comment by XiaoHZhuaWaWa** [comment]
So, I'll check my code for myself. Thanks ,bye

**Comment by AndreHaueisen** [comment]
@Kucingemas 
new version is out. It should eliminate unexpected behavior when dismissing Flushbar in any circumstance.

**Comment by Kucingemas** [comment]
thankyou for the updates!

**Comment by quetool** [comment]
Can anyone please post an example on how to do this? I am not being able!
I mean, how to dismiss a flushbar when I need to show anotherone. I am using flushbar to show notifications

**Comment by AndreHaueisen** [comment]
Dismiss the previous one first. You can even concatenate them. `dimiss()` returns a Future that is completed when the bar is dismissed.

**Comment by quetool** [comment]
Yeah but I am not able to achieve the behaviour I want.
I mean, if suddlenly arrive many push notifications at the same time, I am not able to show them all. I think I need to create some kind of "pool" (an array maybe) of notifications...

**Comment by AndreHaueisen** [comment]
To dismiss them correctly, you have to keep the reference to each one of them and dismiss them LIFO stile.
You could also create a stream and delay the next one until the current is dismissed. [RxDart](https://pub.dartlang.org/packages/rx_command) can help you achieve this.

**Comment by quetool** [comment]
It's just what I am trying to do! LOL
I am trying first with a simple solution, I will involve RxDart later if I do not have success with this...

```
List<Flushbar> notifications = List();
Flushbar currentFlushbar;
FlushbarStatus currentStatus = FlushbarStatus.DISMISSED;

fifoNotifications(BuildContext context) {
  if (this.notifications.length != 0 && this.currentStatus == FlushbarStatus.DISMISSED) {
    Future.delayed(Duration.zero, () {
      this.currentFlushbar = this.notifications[0];
      this.notifications.removeAt(0);
      this.currentFlushbar.show(context);
      this.currentFlushbar.onStatusChanged = (FlushbarStatus status) {
        this.currentStatus = status;
        if (status == FlushbarStatus.DISMISSED) {
          fifoNotifications(context);
        }
      };
    });
  } else {
    print("NO MORE");
  }
}
```

it's a kind of FIFO algorithm... I am waiting the first one to hide in order to show the next one

**Comment by AndreHaueisen** [comment]
There is a bug somewhere else. I was able to make it work [here](https://drive.google.com/file/d/1caonlO9QF13hynvyIKn86zNWK2sRX1BI/view?usp=sharing)

**Comment by quetool** [comment]
That’s great. But in your example if I show in order 0, 1, 2, 3 I need to dismiss in order 0, 1, 2, 3
Is that possible?

**Comment by AndreHaueisen** [comment]
The last one to show has to be the first one to go (Last In First Out). If you obey this rule you won't have a problem.

**Comment by quetool** [comment]
Thanks, last question: is it possible to “cancel” a flushbar opening action? Perhaps on it’s IS_APPEARING status? I mean, what about if I get a looot of push notifications... I am not comfortable with a LIFO solution and I am trying to find another way... I am thinking about “cancelling” one flushbar to being opened if another notification arrives in that moment

**Comment by AndreHaueisen** [comment]
After version 1.3.0, it is now possible to dismiss a Flushbar that is not the top route. The only inconvenient is that it will not animate back (simply disappear) and the listener, if used, will not register the dismissal.

**Comment by quetool** [comment]
Great news! Thanks @AndreHaueisen !
