### ISSUE TITLE
Possibility to start animation on top of bottom navigation

### ISSUE THREAD

**Issue by felixgabler** [AndreHaueisen/flushbar#112]
I am using a bottom navigation element and would like to be able to specify the starting position for the Flushbar to animate in from. Right now it always start from the bottom and moves over the bottom navigation bar which is not very beautiful. Is there a way to specify where it should start?

**Comment by wiradikusuma** [comment]
Just to ensure I'm voting the same issue: What you want is to show flushbar right above bottom navigation bar instead of overlapping it @felixgabler ?
