### ISSUE TITLE
Error building with flutter 1.14.6

### ISSUE THREAD

**Issue by ahmaducg** [AndreHaueisen/flushbar#113]
```
Compiler message:
../../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:273:8: Error: The method 'FlushbarRoute.install' has more required arguments than those of overridden method 'OverlayRoute.install'.
  void install(OverlayEntry insertionPoint) {
       ^
../../Flutter_SDK/packages/flutter/lib/src/widgets/routes.dart:40:8: Context: This is the overridden method ('install').
  void install() {
       ^
../../Flutter_SDK/.pub-cache/hosted/pub.dartlang.org/flushbar-1.9.1/lib/flushbar_route.dart:281:18: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    super.install(insertionPoint);
                 ^
```

**Comment by thevinou** [comment]
Same error here, after flutter upgrade.

A fix would be very welcome.

Thanks

**Comment by FabioWolfen** [comment]
Edit
`flushbar-1.9.1/lib/flushbar_route.dart`

Line 273
`void install() {`

And line 281
`super.install();`

**Comment by ThinkDigitalSoftware** [comment]
This is happening because the newest flutter version changed the function signature for the `OverlayRoute.install` method.
```dart
 @override
  void install() {
    assert(_overlayEntries.isEmpty);
    _overlayEntries.addAll(createOverlayEntries());
    super.install();
```

**Comment by MarioMoraes** [comment]
Find the file flushbar-1.9.1/lib/flushbar_route.dart??

**Comment by Promise4235** [comment]
Greeting all,

I'm having the same issue, does anyone have a working solution.

Thanks.

**Comment by ThinkDigitalSoftware** [comment]
Downgrade to stable...

On Feb 17, 2020 12:58 AM, Promise4235 <notifications@github.com> wrote:

Greeting all,

I'm having the same issue, does anyone have a working solution.

Thanks.

**Comment by Giuliano-Stravini** [comment]
If you don't want downgrade, just edit flushbar_route.dart like @FabioWolfen commented above

> Edit
> flushbar-1.9.1/lib/flushbar_route.dart
> 
> Line 273
> void install() {
> 
> And line 281
> super.install();

This file is inside of your flutter path 
"%YOURFLUTTERPATH% \.pub-cache\hosted\pub.dartlang.org\flushbar-1.9.1\lib\flushbar_route.dart"

Works fine to me, while don't have update in the package

**Comment by Giuliano-Stravini** [comment]
I was browsing the issues and i found this #110 . It's the same problem.

@valterh4ck3r did a fork of package with this "correction".
To use it, just put in your pubspec.yaml

```
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master
```

By the way, already have merged in master this change in this package, but wasn't released a version (PR #111 )

**Comment by sjghose** [comment]
Is broken on Flutter 1.15..22-pre.24 used the git referenced version and compiled like a charm. Thank you.

**Comment by djpnewton** [comment]
fix is committed but not released, try importing like so:

 ```
flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar.git
      ref: 13c55a8
```

**Comment by Kav47** [comment]
> fix is committed but not released, try importing like so:
> 
> ```
> flushbar:
>    git:
>      url: https://github.com/AndreHaueisen/flushbar.git
>      ref: 13c55a8
> ```

Thank you! This works.
getting the same error on beta channel, 1.15.17.

**Comment by MarcoNPZ** [comment]
> fix is committed but not released, try importing like so:
> 
> ```
> flushbar:
>    git:
>      url: https://github.com/AndreHaueisen/flushbar.git
>      ref: 13c55a8
> ```

This doesn't work for me, unfortunately. I added it exactly like this to the end of pubspec.yaml :(

**Comment by Kav47** [comment]
try flutter clean, then pub get.

**Comment by Kav47** [comment]
Okay, so I guess the 'stable' channel have some issues with this. Switching to 'beta' or 'dev' solves this problem.

`flutter channel dev` at the moment beta have some [issue with the dropdownButton](https://github.com/flutter/flutter/issues/52018).
`flutter upgrade`

then 
```
flushbar:
   git:
     url: https://github.com/AndreHaueisen/flushbar.git
     ref: 13c55a8
```
copy the above bit in your `pubspec.yaml` instead of `flushbar: xxxxx`

**Comment by Selecao** [comment]
> Okay, so I guess the 'stable' channel have some issues with this. Switching to 'beta' or 'dev' solves this problem.
> 
> `flutter channel dev` at the moment beta have some [issue with the dropdownButton](https://github.com/flutter/flutter/issues/52018).
> `flutter upgrade`
> 
> then
> 
> ```
> flushbar:
>    git:
>      url: https://github.com/AndreHaueisen/flushbar.git
>      ref: 13c55a8
> ```
> 
> copy the above bit in your `pubspec.yaml` instead of `flushbar: xxxxx`

Absolutely working. 'stable' channel still have issues, but 'dev' work perfect.

**Comment by Faiyyaz** [comment]
Even i am getting the same error with flushbar: ^1.10.0 this version on flutter v1.12.13

**Comment by AndreHaueisen** [comment]
Fix was release in version 1.10. 
Please, read the changelog before using this version.

**Comment by vedantrathore** [comment]
@AndreHaueisen I have version 1.10 of the flushbar library as mentioned in my pubspec.yaml file

```
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  flushbar: ^1.10.0
```

I'm still getting this error while running the build

```
Compiler message:
../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:303:8: Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
../../../tools/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
../../../tools/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:311:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max
```

Any specific reason why this it's still giving me an error after the fix has been incorporated in the v1.10? Do correct me if I'm missing something here.

**Comment by AndreHaueisen** [comment]
You are using flutter stable version. Use the beta one or go to flushbar 1.9. I explained it in the changelog

**Comment by guihackmann** [comment]
I tried both beta version and 1.9m ,and still have the issue.

Also, I don't understand one of the suggested things (below). What is to be edited (from what to what)?

"flushbar-1.9.1/lib/flushbar_route.dart

Line 273
void install() {

And line 281
super.install();"

**Comment by jogapps** [comment]
The package is still not working. I've tried both github, and pub.dev package. Its yet to work. Fix this package please, a lot of projects depend on this package

**Comment by tusharchetan** [comment]
Same problem with me since the day I changed my flutter channel from stable to beta and then master. It worked for me when i again changed my channel to stable and then used "Flutter Upgrade".
Hope this works for you too

**Comment by jogapps** [comment]
It finally worked. I used 1.9.1 without the caret sign ^

**Comment by rafiqulislam21** [comment]
This works for me:
https://github.com/AndreHaueisen/flushbar/issues/110#issuecomment-619368001

**Comment by lordzyx** [comment]
> This works for me:
> [#110 (comment)](https://github.com/AndreHaueisen/flushbar/issues/110#issuecomment-619368001)

YES! You saved me.

Remove ^ from ^1.9.1 - 
Only 1.9.1 it's working for me

**Comment by iPatel007** [comment]
Found the solution.

In the project you ,

**External Libraries -> Dart Packages -> flushbar-version -> flushbar_route.dart**

There is line at 316

```
@override
  void install() {....

```
change 

```
@override
  void install(OverlayEntry insertionPoint) { .....
```

and before end the function  at the line 326
  
```
  super.install();
}
```
change 

```
  super.install(insertionPoint);
}
```

That's it!
