### ISSUE TITLE
install() 没有传参数，编译报错

### ISSUE THREAD

**Issue by php110** [AndreHaueisen/flushbar#118]
@override
  void install() {
    assert(!_transitionCompleter.isCompleted, 'Cannot install a $runtimeType after disposing it.');
    _controller = createAnimationController();
    assert(_controller != null, '$runtimeType.createAnimationController() returned null.');
    _filterBlurAnimation = createBlurFilterAnimation();
    _filterColorAnimation = createColorFilterAnimation();
    _animation = createAnimation();
    assert(_animation != null, '$runtimeType.createAnimation() returned null.');
    super.install();
  }
文件 flushbar_route.dart
1.10没参数，编译报错，查看1.9.1的文件里是有参数的！

**Comment by AndreHaueisen** [comment]
Please, read the changelog.

**Comment by omar-khaium** [comment]
try `flushbar: 1.6.0`
It workes for me. Also, check the changelogs for the compatible version for you.
