### ISSUE TITLE
Flushbar 1.10 won't compile

### ISSUE THREAD

**Issue by TheFe91** [AndreHaueisen/flushbar#119]
**Describe the bug**
As soon as you install version 1.10 the compiler stops compiling, reporting the error below

**Paste relevant code**
`Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.`

**Screenshots **
![Schermata 2020-03-27 alle 10 58 16](https://user-images.githubusercontent.com/21155677/77744413-e6fc2900-7019-11ea-89e0-f6f0c104fef5.png)

**Comment by AndreHaueisen** [comment]
Read the changelog

**Comment by TheFe91** [comment]
OK, sorry, didn't see!

**Comment by AndreHaueisen** [comment]
No problem mate

**Comment by omar-khaium** [comment]
try `flushbar: 1.6.0`
It workes for me. Also, check the changelogs for the compatible version for you.
