### ISSUE TITLE
Issues in lib/flushbar_route.dart 

### ISSUE THREAD

**Issue by m8iog** [AndreHaueisen/flushbar#122]
Hi, 

I'm using your flushbar, but after updating flutter I've got an issue - same as the reported health issue on https://pub.dev/packages/flushbar#-analysis-tab-

I just wondered - is this something you are working on fixing? Thank you!

**Comment by robertoltrocha** [comment]
I am unable to publish the new version of my App because I have the same problem for the iOS reported above. Any predictions for solving the problem?
My entire app has dialogues using this plugin. It would be too much work to change everything.
I appreciate your help. version 1.10.0

**Comment by AndreHaueisen** [comment]
Please, read the changelog.
If you are not using flutter beta, go back to version 1.9.1

**Comment by robertoltrocha** [comment]
I was using version 1.9.1 and had this problem and for that reason I switched to version 1.10.0. This problem happened after I upgraded the flutter. I have no way to inform the version of the flutter now, but it is the last stable version. I upgraded yesterday. Only iOS I had this issue. Android is ok.

**Comment by AndreHaueisen** [comment]
If you are on stable, use version 1.9.1

**Comment by rafidkotta** [comment]
In `pubspec.yaml`
change `flushbar: ^1.9.1` to `flushbar: 1.9.1` 
which sets package version to specific value only.
`^` is used to get updated version from package library.

I hope this helps somebody :)
@robertoltrocha
