### ISSUE TITLE
Version 1.10.0 - Install problem - READ THE CHANGELOG BEFORE OPENING AN ISSUE

### ISSUE THREAD

**Issue by josephviq** [AndreHaueisen/flushbar#123]
Compiler message:
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.10.0/lib/flushbar_route.dart:303:8: Error: The method 'FlushbarRoute.install' has fewer positional arguments than those of overridden method 'OverlayRoute.install'.
  void install() {
       ^
/D:/flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.10.0/lib/flushbar_route.dart:311:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 784

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by AndreHaueisen** [comment]
As I explained in the changelog, go back to version 1.9.1 if you are using Flutter stable

**Comment by uwejan** [comment]
@AndreHaueisen flutter packages get, always get 1.10.0 not matter i clean the cache or usie other version. 
it always keep downloading 1.10.0.
please advice.

**Comment by resfandiari** [comment]
> @AndreHaueisen flutter packages get, always get 1.10.0 not matter i clean the cache or usie other version.
> it always keep downloading 1.10.0.
> please advice.

try flushbar: 1.6.0
I have same problem ,It workes for me.

**Comment by davydany** [comment]
@resfandiari I had the same issue... remove `flushbar 1.10.0` from your pub cache (as shown below) and then run `flutter pub get`. That fixed it for me.

```bash
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0
```

**Comment by DotoPototo** [comment]
Why, if this has breaking changes, is the version not set to 2.0.0... semantic versioning is there for a reason, to prevent issues like this happening where people upgrade without meaning to. @AndreHaueisen

**Comment by uwejan** [comment]
> > @AndreHaueisen flutter packages get, always get 1.10.0 not matter i clean the cache or usie other version.
> > it always keep downloading 1.10.0.
> > please advice.
> 
> try flushbar: 1.6.0
> I have same problem ,It workes for me.

`Invalid version constraint: Expected version number after "^" in "^1.6", got "1.6".`
has to be 1.6.0
and still it downloads 1.10.0
am removing this package for good.

**Comment by Lorcan-Bowens** [comment]
> > > @AndreHaueisen flutter packages get, always get 1.10.0 not matter i clean the cache or usie other version.
> > > it always keep downloading 1.10.0.
> > > please advice.
> > 
> > 
> > try flushbar: 1.6.0
> > I have same problem ,It workes for me.
> 
> `Invalid version constraint: Expected version number after "^" in "^1.6", got "1.6".`
> has to be 1.6.0
> and still it downloads 1.10.0
> am removing this package for good.

Same problem over here

**Comment by joandervieira** [comment]
> > > > @AndreHaueisen flutter packages get, always get 1.10.0 not matter i clean the cache or usie other version.
> > > > it always keep downloading 1.10.0.
> > > > please advice.
> > > 
> > > 
> > > try flushbar: 1.6.0
> > > I have same problem ,It workes for me.
> > 
> > 
> > `Invalid version constraint: Expected version number after "^" in "^1.6", got "1.6".`
> > has to be 1.6.0
> > and still it downloads 1.10.0
> > am removing this package for good.
> 
> Same problem over here

It works for me:

`flushbar: <1.9.1`

**Comment by AndreHaueisen** [comment]
With Flutter now on version 1.17, this issue is fixed

**Comment by BroPet89** [comment]
Upgrading Flutter to 1.17 **caused** this issue to appear for me
