### ISSUE TITLE
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.10.0/lib/flushbar_route.dart:303:8:

### ISSUE THREAD

**Issue by boungly** [AndreHaueisen/flushbar#127]
**Library Version**
flushbar: ^1.10.0

**Describe the bug**
I don't know if I missed any part from [Library](https://pub.dev/packages/flushbar)  but there's sth wrong with I copy the code.

**Paste relevant code**
```
BaseButton(
    text: "Login",
    onButtonTapHandler: () {
        Flushbar(
            title: "Hey Ninja",
            message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            duration: Duration(seconds: 3),
        ).show(context);
    },
),
```

**Screenshots **
I got this error instantly after I run the project `flutter run`.
![image](https://user-images.githubusercontent.com/25840592/79685498-81d7d400-8263-11ea-9e28-53e97fa9d1fa.png)

Thanks for the feedback :)

**Comment by ghost** [comment]
I rolled back to older and then OK
![image](https://user-images.githubusercontent.com/12295611/79689271-c40e0f00-827d-11ea-9722-48c374f5f7ca.png)

**Comment by boungly** [comment]
@thieutu so which version should I use? as `flushbar: ^1.10.0` still got same problem.

**Comment by guptahitesh121** [comment]
I also get the same error.

**Comment by azack** [comment]
see #123

**Comment by AndreHaueisen** [comment]
With Flutter now on version 1.17, this issue is fixed
