### ISSUE TITLE
Clicking on the last box does not disappear.

### ISSUE THREAD

**Issue by XiaoHZhuaWaWa** [AndreHaueisen/flushbar#13]
Clicking on the last box does not disappear.
I didn't solve your problem yesterday. Please take a look and use your demo urgently.

**Comment by AndreHaueisen** [comment]
Hi @XiaoHZhuaWaWa 
I did not understand your problem. What do you mean by last box? Could you elaborate?

**Comment by XiaoHZhuaWaWa** [comment]
one button， I clicked many times, the flushbar, one will not disappear。
` Flushbar()
          ..message = args[0]
          ..duration = Duration(seconds: 3)
          ..show(context);`
![screenshot_1537260674](https://user-images.githubusercontent.com/32632245/45953712-84e5f080-c03d-11e8-9eab-0a0f064f4597.png)

**Comment by AndreHaueisen** [comment]
This is a known bug and I'm working on it. There are ways you can avoid spamming Flushbar. Take a look at this [issue](https://github.com/AndreHaueisen/flushbar/issues/11#issue-361558440)

**Comment by XiaoHZhuaWaWa** [comment]
ok，thankyou
