### ISSUE TITLE
Get Error when Flutter is  v1.12.13

### ISSUE THREAD

**Issue by gybin02** [AndreHaueisen/flushbar#139]
../../flutter/packages/flutter/lib/src/widgets/routes.dart:41:8: Context: This is the overridden method ('install').
  void install(OverlayEntry insertionPoint) {
       ^
../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flushbar-1.10.2/lib/flushbar_route.dart:326:18: Error: Too few positional arguments: 1 required, 0 given.
    super.install();
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

[✓] Flutter (Channel unknown, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)

**Comment by cgrain** [comment]
Yeah, this is a breaking change in flushbar 1.10, it needed this change for Flutter 1.15, either downgrade to flushbar 1.9 or upgrade to the latest stable flutter (1.17). It is explained better than that I can do in the changelog: https://pub.dev/packages/flushbar#-changelog-tab-

**Comment by AndreHaueisen** [comment]
Update your flutter version
