### ISSUE TITLE
error: Target of URI doesn't exist: 'package:flushbar/flushbar.dart'

### ISSUE THREAD

**Issue by alexlovar** [AndreHaueisen/flushbar#14]
Hi, i can't install on my app , i get this error on dart analysis.
i added the pubspec dependecie and import the package into the dart file, but i get this:
error: Target of URI doesn't exist: 'package:flushbar/flushbar.dart'. (uri_does_not_exist at .......)
flutter doctor -v
[√] Flutter (Channel dev, v0.9.2, on Microsoft Windows [VersiÃ³n 10.0.14393], locale es-US)
    • Flutter version 0.9.2 at c:\flutter
    • Framework revision 85b4670b2a (7 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Alex\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (2 available)
    • ONE E1005 • 1ab62aa4 • android-arm   • Android 7.1.2 (API 25)
    • MIX       • 6539389a • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by AndreHaueisen** [comment]
@alexlovar hi.
I was using the beta channel, changed to the master channel and I did not find any problems.
There are some things you can check though:
- did you run `flutter packages get`?
- did you try restarting the IDE?
- did you try running `flutter clean`?

Please, let me know if you found the issue
