### ISSUE TITLE
Allow for alignment in custom Text values

### ISSUE THREAD

**Issue by whitfin** [AndreHaueisen/flushbar#15]
Hi! Great library, very convenient :) 

I've been wondering if it's worth adding a binding in Flushbar to allow people to align their text. For example:

```dart
Flushbar(
  messageText: const Text(
    'Check this out!',
    textAlign: TextAlign.center
  )
);
```

This has no effect currently, because the `Text` doesn't scale to the width of the screen - and as far as I can tell, there's no way to actually enforce this from outside of the Flushbar library itself. It looks like we'd just have to wrap the actual messageText in some container that allows for maximum width. Perhaps it could be an additional option? 

If you think this is worth it, I might be able to take a shot at it if needed! It appears (at least to me) to look nicer if shorter messages (such as the example above) can be aligned into the center.

**Comment by whitfin** [comment]
This actually might be as simple as using `CrossAxisAlignment.stretch` in the `Column`s containing the `messageText`, although I haven't tried it out yet. I'm wondering if it's even worth an option, considering that the default behaviour is the same (you're kinda opting into this by using `textAlign` in the first place).

**Comment by AndreHaueisen** [comment]
Hi @whitfin 
You make a good point. Thank you very much for your help!
Cheers!
