### ISSUE TITLE
I keep getting this error anytime the flushbar shows 

### ISSUE THREAD

**Issue by joeyyy688** [AndreHaueisen/flushbar#168]
![AD2A4A9A-AE45-4CE7-86F3-B3F7CF80D39D](https://user-images.githubusercontent.com/70595863/101292707-1c901d80-3809-11eb-8242-52a015eb63b0.png)
![730E53B0-CE05-453A-9FE1-0DB805DD5885](https://user-images.githubusercontent.com/70595863/101292717-2580ef00-3809-11eb-84e7-9d68cc8e26ac.png)

**Comment by MostafaDadkhah** [comment]
i have this issue too

**Comment by bartonhammond** [comment]
Me too.  Used to work.

**Comment by sterrenburg** [comment]
This happens in a new project that is using `auto_route`. This is on the beta branch:
```shell
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.17134.1902])
    • Flutter version 1.24.0-10.2.pre at /flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

```

**Comment by jayeshpansheriya** [comment]
its not maintenance from long time,
you can also use https://pub.dev/packages/awesome_extensions, with some extra feature and with extension, as well as null safety support.
