### ISSUE TITLE
Is this great plugin still supported? ❤️ Last commit 8 months ago :(

### ISSUE THREAD

**Issue by eggnstone** [AndreHaueisen/flushbar#173]
Is this great plugin still supported? 
Last commit 8 months ago :(
Also nullsafety would be great.
❤️

**Comment by eggnstone** [comment]
I guess not supported anymore, because it is now marked "discontinued" on pub.dev.
Is "another_flushbar" a direct continuation?

**Comment by cirediew** [comment]
Check #170

**Comment by eggnstone** [comment]
Thanks but that's not an official endorsement by the original creator(s).
It would be nice to hear an official statement from them.

**Comment by mikeesouth** [comment]
I can no longer find this package using pub.dev search. Not sure when and how packages are removed from that page: https://pub.dev/packages?q=flushbar

**Comment by eggnstone** [comment]
You can find it if you enable "discontinued" under "advanced"
https://pub.dev/packages?q=flushbar&discontinued=1

**Comment by eggnstone** [comment]
Marked as discontinued therefore the answer is "no". Closing this issue now.
