### ISSUE TITLE
Is there any way to give it to border radius? 

### ISSUE THREAD

**Issue by ghost** [AndreHaueisen/flushbar#18]
This is not an issue but is there any way to make it rounded? 
Like this image for iOS.
Thank you for the great plugin I really appreciate it!
![2018-11-09 13 56 46](https://user-images.githubusercontent.com/41893584/48244134-5d00ef80-e427-11e8-89b7-5100e8bcb373.png)

**Comment by AndreHaueisen** [comment]
Hi @Daibaku0615 
Currently, there is no way to do that but I think it would be a nice feature. Will try to implement it in the following weeks. Thanks for your interest.

**Comment by lifenautjoe** [comment]
Would be awesome to have this!

**Comment by ghost** [comment]
Sorry for late response.
Thank you so much I'll look forward to it.
Thanks again for great plugin!

**Comment by AndreHaueisen** [comment]
@Daibaku0615 I published version 1.1.0 with two new features: aroundPadding and borderRadius
Please, try it out. I'm waiting for your feedback.
Cheers

**Comment by ghost** [comment]
Sorry for late response and I just checked it out.
I found it wonderful!
I really appreciate it.
Thank you so much for great feature keep up the great work:)
