### ISSUE TITLE
Automatically adapt the width of the text？

### ISSUE THREAD

**Issue by stoneLee81** [AndreHaueisen/flushbar#180]
![image](https://user-images.githubusercontent.com/18001708/115211275-fc1a8d00-a131-11eb-93e9-cc34ee7e2db3.png)
Whether it is supported or not, it will automatically adapt to the displayed width according to the number of characters. Currently, a fixed width is set. When the characters are not enough, there will be extra parts, which is not beautiful enough

**Comment by hmarat** [comment]
> ![image](https://user-images.githubusercontent.com/18001708/115211275-fc1a8d00-a131-11eb-93e9-cc34ee7e2db3.png)
> Whether it is supported or not, it will automatically adapt to the displayed width according to the number of characters. Currently, a fixed width is set. When the characters are not enough, there will be extra parts, which is not beautiful enough

Did you find any solution?

**Comment by stoneLee81** [comment]
> > ![image](https://user-images.githubusercontent.com/18001708/115211275-fc1a8d00-a131-11eb-93e9-cc34ee7e2db3.png)
> > Whether it is supported or not, it will automatically adapt to the displayed width according to the number of characters. Currently, a fixed width is set. When the characters are not enough, there will be extra parts, which is not beautiful enough
> 
> Did you find any solution?
I modify the code to solve this issue, but I found this widget will cover the screen, so I changed another one.
