### ISSUE TITLE
Is this discontinued? what are the alternatives?

### ISSUE THREAD

**Issue by lnk3** [AndreHaueisen/flushbar#182]

**Comment by RobertoNegro** [comment]
In pub.dev it's tagged as discontinued. If you really need to use this library, you can use [https://pub.dev/packages/another_flushbar](https://pub.dev/packages/another_flushbar) which is the same library but it's maintained by another user and updated to support null safety.

As an alternative, you can use SnackBar class, which is built in Flutter: [https://api.flutter.dev/flutter/material/SnackBar-class.html](https://api.flutter.dev/flutter/material/SnackBar-class.html)

**Comment by lnk3** [comment]
I was actually using the built in library but yours seemed more "complete".
I will check out the `another_flushbar` package.
Thank you I think we can close this thread.
