### ISSUE TITLE
[Feature request] Custom icon

### ISSUE THREAD

**Issue by lifenautjoe** [AndreHaueisen/flushbar#19]
Hey there,

First of all, thanks for creating this great library :-). 

In my current project we have a custom IconSet, which we would like to use with this, however the implementation has the icon argument locked to being a material `Icon`. 

Is there any chance of being able to provide a custom one? 

Cheers,
Joel.

**Comment by AndreHaueisen** [comment]
@lifenautjoe Hi. Thanks man!

You can use any Icon you want. You only have to make sure to pass in the right IconData
If you need Cupertino icon for examples, you need to include `cupertino_icons: ^0.1.2` dependency (make sure you run 'flutter clean' after adding the dependency) so you can use:

```
icon = Icon( CupertinoIcons.eye, ) // for example
```

Here is an [example](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/icons.dart) on IconData

**Comment by lifenautjoe** [comment]
Hi Andre,

Thanks for the reply!

I meant completely custom Icons, not built by the flutter team.

Could be anything arbitrary, like an `Image` or even a `Text` widget.

It's the same principle as flutter does with their buttons or navigation bars in which they allow any kind of Widget to be placed as an icon.

**Comment by AndreHaueisen** [comment]
That would require accepting a Widget instead of Icon as an argument. I'm not sure I'm comfortable with the idea. Sometimes a lot of customization can make things overly complicated. Let me make some tests and think about it a bit more.

**Comment by lifenautjoe** [comment]
Hi Andre,

Thanks for your reply.

Hope you can consider it. For me it’s one of the amazing things about the
official flutter widgets, the incredible amount of customization possible.

Cheers,
Joel.

**Comment by AndreHaueisen** [comment]
@lifenautjoe 
Version 1.1.2 includes your request.
Thanks for your feedback.

**Comment by lifenautjoe** [comment]
Awesome ! Great job!
