### ISSUE TITLE
Error when swipeback when flushbar still appear (IOS)

### ISSUE THREAD

**Issue by digarahayu17** [AndreHaueisen/flushbar#2]
this is good library currently that i use, but i got some odd behavior when flushbar show in i swipe back to previous screen i go error , maybe there is something to do in super.dispose();

**Comment by AndreHaueisen** [comment]
Hi @digarahayu17 . Can you paste the error and your flutter doctors, please?

**Comment by digarahayu17** [comment]
@AndreHaueisen  ok, actually the flutter up to date and there is not alert error from my apps but  when i swipe back to previous screen i can do anything like go to next screen or something else (the condition is swipe when flushbar still appear).
Here is log error

`flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown while notifying status listeners for AnimationController:
flutter: Cannot reuse a MaterialPageRoute<dynamic> after disposing it.
flutter: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 215 pos 12:
flutter: '!_transitionCompleter.isCompleted'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TransitionRoute.didPopNext (package:flutter/src/widgets/routes.dart)
flutter: #3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1691:23)
flutter: #4      Navigator.pop (package:flutter/src/widgets/navigator.dart:1072:34)
flutter: #5      new _FlushbarState.<anonymous closure> (package:flushbar/flushbar.dart:159:50)
flutter: #6      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
flutter: #7      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:531:7)
flutter: #8      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:547:5)
flutter: #9      Ticker._tick (package:flutter/src/scheduler/ticker.dart:229:5)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
flutter: #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:363:8)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
flutter: #15     _invoke1 (dart:ui/hooks.dart:134:13)
flutter: #16     _beginFrame (dart:ui/hooks.dart:105:3)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The AnimationController notifying status listeners was:
flutter:   AnimationController#48f7d(⏮ 0.000; paused)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1437 pos 12: '!_debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      NavigatorState.push (package:flutter/src/widgets/navigator.dart)
#3      Navigator.push (package:flutter/src/widgets/navigator.dart:816:34)
#4      _LoginPageState._navigateAndDisplaySelection (package:form_login/pages/login.dart:178:36)
<asynchronous suspension>
#5      _LoginPageState.build.<anonymous closure> (package:form_login/pages/login.dart:156:17)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#9      TapGestureRecognizer._chec<…>
`

**Comment by AndreHaueisen** [comment]
@digarahayu17 are you trying to reuse the Flushbar instance after it reaches disposed? FYI, it reaches the disposed state every time the user stops seeing it. 
After it reaches that state, you will need to create a new instance.

**Comment by diegoveloper** [comment]
I'm on flutter master branch and when I try to integrate the package I get this error:

The current Dart SDK version is 2.0.0-dev.69.0.flutter-937ee2e8ca.

Because myproject depends on flushbar >=0.2.6 which requires SDK version >=2.0.0-dev.52.0 <=2.0.0-dev.63.0.flutter-4c9689c1d2, version solving failed.
pub get failed (1)
exit code 1

**Comment by AndreHaueisen** [comment]
@diegoveloper flushbar will only work on dev or beta channels. I do not intend to support master channel for now. This is a different issue. Please, open a new thread.

**Comment by AndreHaueisen** [comment]
@digarahayu17 I'm assuming that your problem was solved. I'm closing this issue for now. If I'm wrong, send a message so I can reopen it.
