### ISSUE TITLE
Bar doesnt hide anymore after calling two snackbar.

### ISSUE THREAD

**Issue by SRCThor** [AndreHaueisen/flushbar#21]
**Describe the bug**
After firing another call to show a flushbar, the previous doesnt dissapear and stays infinitely long.

**Paste relevant code**
<pre>
 /// Displays a snackbar message for the current scaffold.
  void showInSnackBar(String value, [String type="Warning", int duration=2]) {
    Flushbar(forwardAnimationCurve: Curves.bounceIn,
      reverseAnimationCurve: Curves.easeOut,)
      ..icon = Icon(
        Icons.info_outline,
        size: 28.0,
        color: Colors.blue[300],
      )
      ..title = type
      ..message = value
      ..duration = Duration(seconds: 2)
      ..show(context);
  }
</pre>

**Screenshots **
 Not really required I think.

**Comment by AndreHaueisen** [comment]
Please, read [this](https://github.com/AndreHaueisen/flushbar/issues/11#issuecomment-422792175)

**Comment by SRCThor** [comment]
Thanks for the quick response. I need to add, I did read it, but thought it was resolved. My bad.
Also, I really like the idea that we get Scaffold-ignorant Snackbars! The thing is, the reason I'd promote this plugin is because it is much easier to maintain than the standard snackbars. 👍 

Adding listeners/subscriptions actually goes against that.
Would it be possible to make an equivalent for `removeCurrentSnackBar()`? I think since we instantiate a new FlushBar every time, the design doesnt allow it, but each similar route should be able to access any previous route created right?

**Comment by AndreHaueisen** [comment]
That is not possible right now because of the way flutter works. You can only remove the top route; nothing between the bottom and the top routes. There is no `removeNamed()` 
Using a `Future` is the way I found to overcome this problem. You have to make you dismissed the first Flushbar before pushing a new one.

**Comment by ravishankarsingh1996** [comment]
You can resolve the this issue by following the same:

> Flushbar _flushbar = Flushbar(
>     flushbarPosition: FlushbarPosition.TOP,
>     forwardAnimationCurve: Curves.bounceIn,
>     reverseAnimationCurve: Curves.easeOut,
>     duration: Duration(seconds: 2),
>     isDismissible: true,
>     aroundPadding: EdgeInsets.only(left: 10.0, right: 10.0),
>     borderRadius: 5.0);
> 

> showSnackBarTop(String message, final context) {
>   if (_flushbar != null) _flushbar.dismiss('/flushbarRoute');
>   _flushbar
>     ..message = message
>     ..backgroundColor = Colors.red
>     ..shadowColor = Colors.red[800]
>     ..show(context);
> }

Always dismiss the **/flushbarRoute** everytime showing a new snackbar.

**Comment by AndreHaueisen** [comment]
@ravishankarsingh1996 I'm afraid you misunderstood. The argument in `Flushbar.dismiss()` is used when you need a result from Flushbar. It returns a future containing that result when the route finishes animating and gets popped.

FYI, Flutter only allows you to pop the topmost route. You can't pop a route by name.

**Comment by AndreHaueisen** [comment]
After version 1.3.0, it is now possible to dismiss a Flushbar that is not the top route. The only inconvenient is that it will not animate back (simply disappear) and the listener, if used, will not register the dismissal.
