### ISSUE TITLE
Duration to show the FlushBar

### ISSUE THREAD

**Issue by MRL-00** [AndreHaueisen/flushbar#22]
Is there a way to specify the speed it takes to show the snackbar?
I would like to speed it up so it shows quicker than what it does normally as i feel it displays slower than the standard snackbar.

Thanks.

**Comment by AndreHaueisen** [comment]
Hi @MattL-NZ 
Currently, there is no way to do that. 
I will make some experiments with this feature. If everything goes ok, I should have a new version by Sunday.

**Comment by AndreHaueisen** [comment]
Released in version 1.2.0
