### ISSUE TITLE
Add support for full bottom fill on iPhone X

### ISSUE THREAD

**Issue by beardo01** [AndreHaueisen/flushbar#24]
Whenever I create a Flushbar on an iPhone X/XS device there is a gap between the bottom of the screen and the Flushbar. Ideally, the background would colour this part of the screen.

**Comment by AndreHaueisen** [comment]
Hi @beardo01 
Can you attach a picture, please?

**Comment by beardo01** [comment]
![img_0366](https://user-images.githubusercontent.com/11054688/50935563-4df2f800-14d1-11e9-8e62-f51022f6d7dd.png)

@AndreHaueisen

**Comment by AndreHaueisen** [comment]
Unless flutter gives me an option to paint the gesture bar, I can't solve this problem. I will do some research to see if that is possible without disrupting the package.
In the meantime, you can use it at `FlushbarPosition.TOP` or give it some `aroundPadding` and
`borderRadius` to try a more simetric feel with the gap.

**Comment by cetorres** [comment]
Right now the bottom appearance has a wrong position on the iPhone X. Look at the attached image.

![simulator screen shot - iphone x - 2019-01-14 at 14 34 58](https://user-images.githubusercontent.com/533661/51136139-c88d8180-1809-11e9-9114-064eb5d50c93.png)

**Comment by AndreHaueisen** [comment]
@cetorres Can you add flutter doctor output here and some code so we can reproduce?
https://github.com/flutter/flutter/issues/26540#issuecomment-454310488

**Comment by AndreHaueisen** [comment]
Closing for lack of response

**Comment by RaulUrtecho** [comment]
Any new about this. I had the same issue with the bottom gap I'd like a way to fill with the snack color.
![snack](https://user-images.githubusercontent.com/42857405/96791534-44910200-13be-11eb-8b88-8b0a04a92d42.jpg)
