### ISSUE TITLE
Give an option to center align the message

### ISSUE THREAD

**Issue by keertipurswani** [AndreHaueisen/flushbar#25]
**Before reporting **
Make sure you restarted the IDE, especially after an update. 
Make sure to perform a clean build, especially after an update. 
If the error persists, you are in the right place.

**Describe the bug**

**Paste relevant code**
Give me a taste of what you are doing so I can be directed towards the error.

**Screenshots **
 If you have some screenshots, that is where you will put them.

Thanks for the feedback :)

**Comment by AndreHaueisen** [comment]
`messageText` accepts a `Text` widget. You can align your text using it.
