### ISSUE TITLE
leftBarIndicatorColor with borderRadius

### ISSUE THREAD

**Issue by quetool** [AndreHaueisen/flushbar#27]
leftBarIndicatorColor bug when you add borderRadius

![img_53ef09b61bb8-1](https://user-images.githubusercontent.com/14978705/52065370-2550a200-2555-11e9-8a0d-68e8ec616916.jpeg)

**Comment by quetool** [comment]
Sorry for this, don't pay attention to it I just read the it is a known issue.

**Comment by vasilich6107** [comment]
@quetool could you provide the source? Is it readme?

```
Adds a radius to all corners of Flushbar. Best combined with [margin]. I do not recommend using it with [showProgressIndicator] or [leftBarIndicatorColor]
```
