### ISSUE TITLE
Add support for Flutter master channel

### ISSUE THREAD

**Issue by diegoveloper** [AndreHaueisen/flushbar#3]
Hello, could you update the constraint of your package to match <3.0.0 ?

**Comment by AndreHaueisen** [comment]
@diegoveloper to do that I would have to subscribe to the master channel. Since I'm working on another project, that could introduce some bugs on that project. I will try to do it and tell you how it goes. If no issues are found, I will push the version asap.

**Comment by diegoveloper** [comment]
@AndreHaueisen thanks

**Comment by AndreHaueisen** [comment]
@diegoveloper see if your problem is fixed with this new version.

**Comment by diegoveloper** [comment]
It works, thanks
