### ISSUE TITLE
Flushbar isn't getting dismissed after duration

### ISSUE THREAD

**Issue by keertipurswani** [AndreHaueisen/flushbar#30]
**Before reporting **
Make sure you restarted the IDE, especially after an update. 
Make sure to perform a clean build, especially after an update. 
If the error persists, you are in the right place.

**Describe the bug**

**Paste relevant code**
Give me a taste of what you are doing so I can be directed towards the error.

**Screenshots **
 If you have some screenshots, that is where you will put them.

Thanks for the feedback :)

**Comment by AndreHaueisen** [comment]
Need some code before I can help you

**Comment by keertipurswani** [comment]
This is my code - 

Flushbar(
        title: null,
        duration: Duration(seconds: 3),
        flushbarPosition: FlushbarPosition.TOP,
        message: 'Back online',
        backgroundColor: Colors.green,
      );

**Comment by AndreHaueisen** [comment]
Your code is fine. Make sure Flushbar is the top route when the time ends. Flushbar calls `Navigator.of(context).pop()` when the time is up. It will pop the top most route.
