### ISSUE TITLE
Support any widget as messageText

### ISSUE THREAD

**Issue by szotp** [AndreHaueisen/flushbar#31]
I would like to use Html widget instead of a Text. Would it be possible to accept and widget as messageText, and not just Text?

**Comment by AndreHaueisen** [comment]
@szotp 
Sorry, not possible. I'm flirting with the idea of allowing a richText widget to display the message though.

**Comment by szotp** [comment]
If you just replaced the type of messageText (from Text to Widget), wouldn't this work the same way while also allowing all kinds of widgets?

**Comment by AndreHaueisen** [comment]
The problem here is not a technical one. Supporting any widget introduces an unnecessary complexity that extrapolates the problem that this package is trying to solve.
