### ISSUE TITLE
onStatusChanged not triggered

### ISSUE THREAD

**Issue by pdefuns** [AndreHaueisen/flushbar#34]
When I listen to onStatusChanged, it never gets triggered. 

```
flushbar.onStatusChanged = (FlushbarStatus status) {
  print('Status: $status');
};
```

`flutter v1.2.1`
`flushbar: ^1.2.4`

**Comment by AndreHaueisen** [comment]
It is working here. Could you paste more code?

**Comment by pdefuns** [comment]
Sorry, can be closed. If using after_layout plugin, it needs to be placed outside of it.
