### ISSUE TITLE
Request: direction of dismiss-swipe

### ISSUE THREAD

**Issue by pdefuns** [AndreHaueisen/flushbar#35]
It would be nice to have the possibility to set swipe-directions

Currently it's left and right to dismiss a Flushbar. 
It would be nice to also have the possibilities to swipe up (FlushbarPosition.TOP) or swipe down (FlushbarPosition.BOTTOM) to dismiss

Btw. great package! 😃👍

**Comment by AndreHaueisen** [comment]
Hi @YAPPDEF 
I appreciate the feedback. Feature coming up in the next version.
Cheers

**Comment by AndreHaueisen** [comment]
Live in version 1.3.0
