### ISSUE TITLE
Flushbar throws a UI error if no message is set

### ISSUE THREAD

**Issue by IrosTheBeggar** [AndreHaueisen/flushbar#36]
This code throws an a UI error on iOS:

```
      Flushbar(
        title:  "Password Reset Failed",
        duration:  Duration(seconds: 3),          
        flushbarStyle: FlushbarStyle.GROUNDED,
        leftBarIndicatorColor: Colors.red[300],
      ).show(context);
```

This works though
```
      Flushbar(
        title:  "Password Reset Failed",
        message:  "",
        duration:  Duration(seconds: 3),          
        flushbarStyle: FlushbarStyle.GROUNDED,
        leftBarIndicatorColor: Colors.red[300],
      ).show(context);
```

What it looks like:
<img width="416" alt="Screen Shot 2019-03-18 at 4 01 16 PM" src="https://user-images.githubusercontent.com/1396994/54569188-1e5fe080-4997-11e9-9fe8-4db5ee33dfe9.png">

**Comment by AndreHaueisen** [comment]
This is telling you that either a `message` or `messageText` is required. You don't need a title though.
If you want a message that looks like a title, just use `messageText` and pass a `TextStyle`.

**Comment by AndreHaueisen** [comment]
I will add an assertion on the next version to see if the `message` is empty. Thanks for the feedback.

**Comment by AndreHaueisen** [comment]
Live on version 1.3.1
