### ISSUE TITLE
Using Bloc and on Error State, can't show Flushbar because framework is already in the process of building widgets

### ISSUE THREAD

**Issue by murphycrosby** [AndreHaueisen/flushbar#38]
When using Bloc, and when it transitions to Error state this is when we want to show the Flushbar.  However, calling .show we get error.  Is there a way to trigger it after everything has been built?

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Overlay-[LabeledGlobalKey<OverlayState>#04d73](state: OverlayState#2d026(entries: [OverlayEntry#53c1f(opaque: true; maintainState: false), OverlayEntry#ea687(opaque: false; maintainState: true), OverlayEntry#82953(opaque: true; maintainState: false), OverlayEntry#d6ccf(opaque: false; maintainState: true), OverlayEntry#8a034(opaque: false; maintainState: false)]))
The widg<…>`

```
@override
  Widget build(BuildContext context) {
    return BlocBuilder(
      bloc: _searchStoreBloc,
      builder: (_, SearchStoreState state) {
        if(state is SearchStoreError) {
          _flushbar = Flushbar(
            flushbarStyle: FlushbarStyle.FLOATING,
            flushbarPosition: FlushbarPosition.BOTTOM,
            backgroundColor: Colors.red,
            aroundPadding: EdgeInsets.all(8.0),
            borderRadius: 8.0,
            message: "Error occurred contacting Server",
            duration: Duration(seconds: 5),
          )..show(context);

          print("print 2");
        }
```

**Comment by AndreHaueisen** [comment]
Sorry mate but I can not help you there. I don't use Bloc.
It looks like you need a wait to check if the widget tree finished building.
One immediate horrible solution I see, is to wrap it in a Timer and delay the execution. 
Check this [discussion](https://github.com/flutter/flutter/issues/16218). Can help you find a better solution.

**Comment by murphycrosby** [comment]
Thanks.  I really didn't think it was an issue on the Flushbar side, but thought maybe you or someone had ran into this issue.

This feels dirty but it works.  I wish I knew why a Future<void> function would work but for some reason it gets ran inline...this is the only way I can get it to run after all of the widgets completed.

```
@override
  Widget build(BuildContext context) {
    return BlocBuilder(
      bloc: _searchStoreBloc,
      builder: (_, SearchStoreState state) {
        print("builder");
        if(state is GeolocationError) {
          print("Build: GeolocationError");
          Future.delayed(Duration(seconds: 0)).then((_) {
            Flushbar(
              flushbarStyle: FlushbarStyle.FLOATING,
              flushbarPosition: FlushbarPosition.BOTTOM,
              backgroundColor: Colors.amber,
              aroundPadding: EdgeInsets.all(8.0),
              borderRadius: 8.0,
              messageText: Text(
                state.error,
                style: TextStyle(
                  color: Colors.black87,
                ),
              ),
              duration: Duration(seconds: 5),
            )..show(context);
          });
```

**Comment by AndreHaueisen** [comment]
No problem. If you find a better solution, please post it so other devs can learn it too. 👍

**Comment by orrios** [comment]
Instead of Future.delayed you could use SchedulerBinding.instance.addPostFrameCallback() so it executes once the build is finished
