### ISSUE TITLE
Question: Use dynamic text in title or message text

### ISSUE THREAD

**Issue by pbasl** [AndreHaueisen/flushbar#39]
Hello;
Can the text in the flushbar be dynamic??

Trying to do something like this, but not working
`Flushbar(
          title:  'Hey ${user.fullName}',
          titleText: Text(user.lastName),
          message:  'You have successfully logged in ...',
          duration:  Duration(seconds: 2),
        )..show(context);
`

**Comment by AndreHaueisen** [comment]
Hi @pbasl 
Short answer, no. To change the text you have to create another instance.
What you can do to show progress is use the built-in progress indicator by setting `showProgressIndicator = true` and then use `progressIndicatorController` to control the progress

**Comment by pbasl** [comment]
Sorry I don't understand what you mean by 'create another instance'??

**Comment by AndreHaueisen** [comment]
Arguments are final. You need to create a new Flushbar if you want to display a new text.
