### ISSUE TITLE
Flutter Awesome

### ISSUE THREAD

**Issue by Solido** [AndreHaueisen/flushbar#4]
Thanks !
If you wish you're welcome to join Awesome Flutter so more people can find your work.
https://github.com/Solido/awesome-flutter

**Comment by AndreHaueisen** [comment]
@Solido I would love that. How can I join?

**Comment by Solido** [comment]
Just fork the repo edit source.md to add your entry and send a PR.

**Comment by AndreHaueisen** [comment]
Will do. Thanks, @Solido
