### ISSUE TITLE
Blocking input

### ISSUE THREAD

**Issue by jasonlaw** [AndreHaueisen/flushbar#40]
Hi @AndreHaueisen ,
When calling the loading in progress flushbar, is it possible to block the UI input? If it is not within the scope of the package, then can you please suggest me how should I do it with flushbar? The flushbar is really cool and I definitely want it to be in my app. 
Thanks in advance.

**Comment by AndreHaueisen** [comment]
Hi @jasonlaw 
I have been thinking about this for a while now and it should be available in the next update. What I'm gonna do is push Flushbar with an overlay that prevents the user to click anywhere else. This will be optional of course.

**Comment by AndreHaueisen** [comment]
Live in version 1.4.0
Please, check the [changelog](https://pub.dartlang.org/packages/flushbar#-changelog-tab-)

**Comment by jasonlaw** [comment]
@AndreHaueisen , thanks for the feature!
Could you please also update the FlushbarHelper.createLoading ?
