### ISSUE TITLE
Selection with flushbar

### ISSUE THREAD

**Issue by jasonlaw** [AndreHaueisen/flushbar#46]
Can I make a selection box like this with flushbar, without using Form?

![image](https://user-images.githubusercontent.com/107820/56635532-91482f80-6698-11e9-98c3-affe2e0a8353.png)

**Comment by jasonlaw** [comment]
Better example:

![image](https://user-images.githubusercontent.com/107820/56635649-e97f3180-6698-11e9-8744-9c99f2be09b0.png)

**Comment by AndreHaueisen** [comment]
Hi @jasonlaw 
No, you can't. Even Form was not put in with that intention. Flushbar accepts only one button. It is made for simple user input and notification.
