### ISSUE TITLE
Elevation and elevation shadow color

### ISSUE THREAD

**Issue by anisalibegic** [AndreHaueisen/flushbar#48]
Hey, thanks for the plugin! Can you add elevation and elevation shadow color properties along with boxShadow?

**Comment by AndreHaueisen** [comment]
Hi @grandpa-guru 
That is already built in [BoxShadow's](https://docs.flutter.io/flutter/painting/BoxShadow-class.html) properties.

**Comment by anisalibegic** [comment]
> Hi @grandpa-guru
> That is already built in [BoxShadow's](https://docs.flutter.io/flutter/painting/BoxShadow-class.html) properties.

If you check [the material source code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/shadows.dart) you will find out that elevation maps to the list of BoxShadow instancies but this plugin accepts only one BoxShadow instance. Two ways of solving:

1. Allow passing the list of BoxShadow instances
2. Add elevation and elevation shadow color to the already existing Material widget int the build method on the line 298

Can you please show an example with the elevation `8` and elevation shadow color `Colors.black54`?

**Comment by AndreHaueisen** [comment]
Ok. That makes sense. Since it is a simple change, I will push a new version supporting a list of BoxShadows latter today. I won't map it to specific elevations though.

**Comment by anisalibegic** [comment]
> Ok. That makes sense. Since it is a simple change, I will push a new version supporting a list of BoxShadows latter today. I won't map it to specific elevations though.

Thank you! Maybe you could add [the material source code](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/shadows.dart) to the property documentation in your code.

**Comment by AndreHaueisen** [comment]
Thanks for the feedback. Change live on version 1.5.0
