### ISSUE TITLE
Using with map view 

### ISSUE THREAD

**Issue by morad00** [AndreHaueisen/flushbar#5]
How can I use it with [map_view](https://pub.dartlang.org/packages/map_view) ? 
I need to show a flushbar always while the marker is moving (like google maps) ?

**Comment by AndreHaueisen** [comment]
Hi @morad00 
Flushbar is not made for that use case. It is made for simple user notifications or inputs.
I recommend that you use the backdrop widget. Read [this](https://medium.com/flutter-io/decomposing-widgets-backdrop-b5c664fb9cf4) post to learn how to use it.

**Comment by morad00** [comment]
I understand you but all I need only a basic Flushbar to show location address only, I don't need that backdrop one + I couldn't implement it inside map_view so I searching for anything to show this adderss

**Comment by AndreHaueisen** [comment]
Well @morad00 , I gave a superficial look at the map_view code. Looks like you could create an indefinite flushbar setting `duration = null` and update the text using a listener. Something like

```
mapView.onAnnotationDragEnd.listen((markerMap) {
      var marker = markerMap.keys.first;
      var location = markerMap[marker]; // The actual position of the marker after finishing the dragging.
      setState( () {
        flushbar.message = location;
      });
      
      print("Annotation ${marker.id} dragging ended");
    });
```

**Comment by morad00** [comment]
@AndreHaueisen That's absolutely true, but unfortunately the main problem is that `MapView.show()` brings up an entire overlay screen, thus, Any Android/IOS view can't be as part of the flutter widget hierarchy. so the flushbar seems to be shown behind the map

**Comment by AndreHaueisen** [comment]
The way flushbar works is that it pushes a new route on top of everything when you call `show()`. The same way a Dialog works. It should be displayed on top of the MapView. I have no clue why it is not working.

**Comment by AndreHaueisen** [comment]
@morad00 
Did you figure out a solution to the problem?
