### ISSUE TITLE
Adding an onTap callback

### ISSUE THREAD

**Issue by aloisdeniel** [AndreHaueisen/flushbar#51]
Thank you ! Great library, love the high customization !

It would be useful to have a way to trigger on action when the bar is tapped (for exemple in case of a notification, to trigger a navigation).

**Comment by AndreHaueisen** [comment]
Hi @aloisdeniel 
I'm glad that you like it.
Doesn't `mainButton` satisfy your needs?

**Comment by aloisdeniel** [comment]
I want the user to trigger the action wherever he taps on the bar (it is how native iOS notifications work, and I want to reproduce this behaviour for in-app notifications).

**Comment by aabanaag** [comment]
We also need this. Users are tapping the bar but the action only happens if they tap the icon (which I placed as the mainbutton).

**Comment by AndreHaueisen** [comment]
Feature live in version 1.7. Use `onTap` callback
