### ISSUE TITLE
Beneath bottomNavigationBar and appBar

### ISSUE THREAD

**Issue by Albert221** [AndreHaueisen/flushbar#52]
Hey,

I want my snackbar to appear over the bottom navigation bar (and under app bar in case of `FlushbarPosition.TOP`). Right now I can achieve this by adding a bigger `aroundPadding`, but the snackbar flies over those widgets and I want it to appear from under them, just like the top of the bottom navigation bar was actually the bottom of the screen.

That's my feature request, I guess other people would be grateful for that too :)

**Comment by AndreHaueisen** [comment]
It is not possible to appear from under them. Flushbar is a new route, and as such, will always be on top of everything else that was there before `show()` is called.
