### ISSUE TITLE
Cannot use Flushbar v.1.5.3

### ISSUE THREAD

**Issue by annalaufey** [AndreHaueisen/flushbar#55]
I am getting the FocusScopeNode error all of a sudden. I see that more people are experiencing this and that there is some major Flutter/Dart update that is causing this. 
All of a sudden, out of the blue today, I suddenly could not run my app. 
I hadn't updated anything that I know of, not the pubspec.yaml or installed a new version of Flutter. 

I've been running flushbar  v1.2.1 and I haven't had any trouble. 
Now that I got this issue, I see that the flushbar was updated today to v1.6.0, probably around the similar time that my code stopped working. 

Here is my Flutter Doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IS)
    • Flutter version 1.5.4-hotfix.2 at /Users/ori.annas/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ori.annas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone Xʀ                 • 473D4A7D-7473-4CAB-87AB-C474EBFAC701 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

This it the error I'm getting
![Screenshot 2019-05-31 at 15 48 47](https://user-images.githubusercontent.com/10061685/58718070-3c48b900-83bc-11e9-8b47-c9da2edd3399.png)

And here is a part of my pubspec.yaml 
![Screenshot 2019-05-31 at 15 51 02](https://user-images.githubusercontent.com/10061685/58718081-410d6d00-83bc-11e9-8989-49f6bd1bd237.png)

I tried using either flushbar v1.2.1 and v.1.5.3, but what ever do, it seems that it still always installs v.1.6.0 and I don't understand why. 
<img width="821" alt="Screenshot 2019-05-31 at 16 00 25" src="https://user-images.githubusercontent.com/10061685/58718596-6058ca00-83bd-11e9-966a-6aa41565c014.png">
 
Why can't I use v.1.2.1 or v.1.5.3 all of a sudden? And what can I do to be able to keep running my app? 

Thank you in advance for the help!

**Comment by AndreHaueisen** [comment]
Use version 1.6.0
Take a look at the changelog.

**Comment by AndreHaueisen** [comment]
If you don't want to leave stable, install it like this
`flushbar: '1.5.3'`

**Comment by annalaufey** [comment]
> If you don't want to leave stable, install it like this
> `flushbar: '1.5.3'`

Thank you Andre! This worked :)

**Comment by AndreHaueisen** [comment]
No problem :)
