### ISSUE TITLE
When in FlushbarStatus.IS_HIDING error throws on user Flushbar dismiss

### ISSUE THREAD

**Issue by therealsuji** [AndreHaueisen/flushbar#58]
Hey there I'm quite new to flutter and I'm using the flushbar as an alternative to the snackbar to show notifications from the top and i wanna say thank you for making this  😄.

now on to the  issue,
When a user dismisses the flushbar by swiping, when flushbarStatus is in IS_HIDING '!debugLocked': is not true gets triggered.To make it more clearer, when the flushbar is going to hide and if the user swipes the flushbar mid hiding that error get triggered. Hope thats clear enough.

. And just to make sure is there a way to change the isDismissible while listening. 

Heres the error
`
I/flutter (23827): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23827): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
I/flutter (23827): _WidgetsAppState#d413d](dirty, state: NavigatorState#8e9a3(tickers: tracking 1 ticker)):
I/flutter (23827): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2176 pos 12: '!_debugLocked':
I/flutter (23827): is not true.
I/flutter (23827): 
I/flutter (23827): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23827): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23827): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23827):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (23827): 
I/flutter (23827): When the exception was thrown, this was the stack:
I/flutter (23827): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:2176:12)
I/flutter (23827): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (23827): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (23827): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23827): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #22     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (23827): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #26     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (23827): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23827): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #38     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (23827): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (23827): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #50     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (23827): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23827): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #64     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #68     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23827): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (23827): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #76     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (23827): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (23827): #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (23827): #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (23827): #80     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (23827): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (23827): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (23827): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (23827): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (23827): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter (23827): #87     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (23827): #88     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (23827): #89     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (23827): (elided 3 frames from class _AssertionError and package dart:async-patch)
I/flutter (23827): ════════════════════════════════════════════════════════════════════════════════════════════════════`

**Comment by AndreHaueisen** [comment]
Hi @therealsujji 
I appreciate the feedback :)
I was able to reproduce the error here. Fix will be available in the next version

**Comment by AndreHaueisen** [comment]
Fix live in version 1.7
