### ISSUE TITLE
FocusAtachment

### ISSUE THREAD

**Issue by yossefEl** [AndreHaueisen/flushbar#60]
***Error***
Error: Type 'FocusAttachment' not found.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
i tried:  flushbar: '1.7.0'
            flushbar: '^1.7.0'
            flushbar: ^1.7.0
but no one of this works

**Comment by AndreHaueisen** [comment]
Change to Flutter beta channel or use version 1.5.3

**Comment by AndreHaueisen** [comment]
https://github.com/AndreHaueisen/flushbar/issues/59
