### ISSUE TITLE
Compiler error, library unusable on version ^1.7.0

### ISSUE THREAD

**Issue by andreddie81** [AndreHaueisen/flushbar#62]
Compiler message:
file:///........./flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.7.0/lib/flushbar.dart:207:3: Error: Type 'FocusAttachment' not found.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
file:///.........../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.7.0/lib/flushbar.dart:207:3: Error: 'FocusAttachment' isn't a type.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
file:///........../flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.7.0/lib/flushbar.dart:228:35: Error: The method 'attach' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///............../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'attach'.
    _focusAttachment = _focusNode.attach(context);
                                  ^^^^^^
file:///............./flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.7.0/lib/flushbar.dart:239:16: Error: The method 'dispose' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///............../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dispose'.
    _focusNode.dispose();
               ^^^^^^^
Compiler failed on /..............flutterProjects/testFlush/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

***** FLUTTER & DART VERSION *****
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (7 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

**** POSSIBLE (not optimal) SOLUTION FOUND ****
downgrade library to 1.5.3 seems to work

**Comment by AndreHaueisen** [comment]
There are at least 4 issues closed with the same complaint.
Please, take a look at the changelog or in the closed issues.
I will leave this open for anyone with the same problem.

**Comment by kkizlaitis** [comment]
Yes, please see #60 and #59 .

**Comment by AndreHaueisen** [comment]
Flutter 1.7.8 hit stable. Version restriction is now removed.
Everyone can now use the latest Flushbar version
