### ISSUE TITLE
Request to allow wider widgets on Icon position

### ISSUE THREAD

**Issue by andreddie81** [AndreHaueisen/flushbar#63]
As soon as trying to add something (for example a piece of text) instead of an icon with the Icon property, the layout breaks.

Will it be possible to allow more flexibility there?

Here comes an screenshot with example.

![image](https://user-images.githubusercontent.com/47588111/59755850-ef545600-9288-11e9-9587-2be27fa19eb8.png)

**Comment by AndreHaueisen** [comment]
There is a warning against that in the main page.
Please, spend some time reading the documentation before opening issues.

**Comment by andreddie81** [comment]
this is a request not an issue, how to ask for requests?

**Comment by AndreHaueisen** [comment]
This is not possible right now or it will disrupt the layout for many users.
If you really want to use a text you can use a smaller font size.

**Comment by andreddie81** [comment]
ok nevermind i will modify it according to my needs, thanks!
