### ISSUE TITLE
Content padding - make it optional

### ISSUE THREAD

**Issue by daniel-v** [AndreHaueisen/flushbar#67]
By default, there is a 16 padding to the content of the Flushbar. I'd be nice if I had the ability to remove padding around the content, to get a tad more extra control. Eg: our design snaps to an increment of 10 instead of the values from material design.

**Comment by daniel-v** [comment]
Hm... Seems like this is not going to be that trivial, quite a few details to consider here. @AndreHaueisen what do you think, what would be a decent approach to do this?

**Comment by AndreHaueisen** [comment]
Live at 1.8.0
