### ISSUE TITLE
Flushbar is hidden behind keyboard

### ISSUE THREAD

**Issue by fhuonder** [AndreHaueisen/flushbar#7]
Hi,

When a Flushbar is shown while the keyboard is open the Flushbar is hidden behind it.
When I use a standard Snackbar instead it is shown above the keyboard.

My expectation is that the Flushbar is shown above the keyboard as well.

Regards,
Florian

**Comment by AndreHaueisen** [comment]
Hi @fhuonder 
I will try to fix it today and notify you when the new version is released.
Thanks for the feedback.

**Comment by AndreHaueisen** [comment]
Version 0.8.3 released. Check if it solved your problems, please.

**Comment by AndreHaueisen** [comment]
Closing it for now. If the problem persists, please let me know.
