### ISSUE TITLE
Add ability to dismiss when clicking/tapping overlay

### ISSUE THREAD

**Issue by mcoolidge** [AndreHaueisen/flushbar#71]
It would be nice to be able to dismiss the alerts/overlay when someone taps or clicks the overlay.

**Comment by AndreHaueisen** [comment]
Live at 1.8.2

**Comment by shadyshrif** [comment]
Just to make it clear the feature that solves this issue is by giving a positive value to `overlayBlur` and make sure that `isDismissible` is true.
