### ISSUE TITLE
OnTap issue

### ISSUE THREAD

**Issue by Paul-Todd** [AndreHaueisen/flushbar#72]
Is the implementation of the onTap function correct?

It works if I do this:

```
(Flushbar fb) {
                      fb.dismiss(true);
                      return () {};
                    },
```

I don't know why I need to return an empty function as this seems to be overkill and it is never used in the code.

Maybe the intention was to return a  Future<T> which could then be chained and tell the caller once the dismiss is complete?

**Comment by AndreHaueisen** [comment]
Hi @Paul-Todd 
Uu my bad there. Will push a fix for that today.
Thanks for reporting.

**Comment by AndreHaueisen** [comment]
Live at 1.8.1
