### ISSUE TITLE
FlushbarRoute required context

### ISSUE THREAD

**Issue by javico2609** [AndreHaueisen/flushbar#73]
Hi. Im the developer of the advanced example, previously this required property did not exist, can you help me to solve this issue ?

```
FlushbarRoute({
    @required this.context,
```

**Comment by AndreHaueisen** [comment]
Hi @javico2609 
Sorry about that. I will release a change removing it later today.
I was making some experiments and ended up leaving it there.
Be advised, it may be needed in the future. I don't know yet.
Will tell you how to proceed if it comes to that.

**Comment by javico2609** [comment]
thx @AndreHaueisen

**Comment by AndreHaueisen** [comment]
Live at 1.8.1
