### ISSUE TITLE
Hide/Remove FlushBar at will

### ISSUE THREAD

**Issue by GonzaloSaad** [AndreHaueisen/flushbar#75]
Hello! 

Awesome job with this widget. It is super useful and great. 

I have a question, is it possible to hide a flushbar at will, and not waiting the set time?

Thank you!

**Comment by AndreHaueisen** [comment]
Thanks @GonzaloSaad 
You can hide it using three techniques:
1- Use a timer and let it run its course
2- Slide it out of the screen if "isDismissible"
3- Call dismiss() at any time on your code

**Comment by GonzaloSaad** [comment]
Perfect. Thank you very much Andre! 

Keep up that awesome work!

**Comment by charleshan** [comment]
@GonzaloSaad is it possible to `dismiss()` from the mainButton?

e.g. dismiss after clicking on the undo button.

**Comment by GonzaloSaad** [comment]
Like the back button on android? I believe yes, with the help of the `WillPopScope` widget.

**Comment by charleshan** [comment]
Oops, my mistake. I meant to ask @AndreHaueisen.

For your question, no. I was asking if it's possible to dismiss a FlushBar programmatically, within the FlushBar's mainButton `onPressed()`.

**Comment by amadeu01** [comment]
@AndreHaueisen is there any global method like `hideCurrentSnackBar` of Snackbars
