### ISSUE TITLE
How can I show flushbar using navigatorKey?

### ISSUE THREAD

**Issue by basketball-ico** [AndreHaueisen/flushbar#79]

**Comment by AndreHaueisen** [comment]
I'm sorry. Navigator key?

**Comment by fstof** [comment]
If I may revive this issue please.

On `MaterialApp` you can provide a `GlobalKey<NavigatorState>` to the `navigatorKey` property. This serves as the root `Navigator` for the app
Many people (including me) use this `NavigatorState` to do navigation.

So what I have is a "NotificationService" that wraps `Flushbar`. This service gets initialised (with BuildContext) before `MaterialApp` so now the `context` in the `NotificationService` does not contain a `Navigator` and thus showing the Flushbar fails.

By providing an overloaded `show` function this could be remedied.
something like this
```dart
Future<T> show(GlobalKey<NavigatorState> navigatorKey) async {
    _flushbarRoute = route.showFlushbar<T>(
      // context: ????
      flushbar: this,
    );

    return await navigatorKey.currentState.push(_flushbarRoute);
}
```

**Comment by cwe1ss** [comment]
It seams like calling `Flushbar().show(navigatorKey.currentState.overlay.context)` does the trick!

Found here: https://stackoverflow.com/a/53350682/5214796
