### ISSUE TITLE
Change width and position of flushbar

### ISSUE THREAD

**Issue by podb-key** [AndreHaueisen/flushbar#81]
According to the Material Design spec, it is allowed to change the width of a snackbar on wider UIs (screens). 

Also, it is considered bad practice to overlap a snackbar with a FAB. The snackbar should appear above the FAB in those cases.

I tried several ways to change the width (e.g. to half the screen width) without having to touch the Flushbar code, but was unsuccessful. Maybay I'm missing something and in that case any hints are more than welcome. 

Otherwise, perhaps it makes sense to add as an option a closure (functional) that accepts a buildcontext and a flushbar and returns a Widget. It would allow the user to wrap said flushbar in whatever other Widget (including e.g. a Positioned or a FractionallySizedBox). Inside Flushbar you would obviously have to render the returned Widget instead of the Flushbar directly.

**Comment by AndreHaueisen** [comment]
About the width, the solution should be straight forward. I will try to make a new release in the next few days.
Now, about the fab, I still don't have a good solution for it. An alternative is to use in the TOP position

**Comment by AndreHaueisen** [comment]
`maxWidth` live at 1.9.0
