### ISSUE TITLE
Flushbar is blocking navigation

### ISSUE THREAD

**Issue by cantaspinar** [AndreHaueisen/flushbar#84]
**Describe the bug**
When Flushbar is displayed, tapping on back button hides the Flushbar instead of navigating  back. Is there a way to navigate back without dismissing the Flushbar?

**Comment by AndreHaueisen** [comment]
Because Flutter routes are a stack and Flushbar is a route, it has to be dismissed before routes bellow it.

**Comment by ampersanda** [comment]
Is there any way to push Flushbar without interfere the current `Navigator.pop`?
It seems that using `navigatorKey` also doesn't solve to this
