### ISSUE TITLE
flush bar not showing on android kitkat

### ISSUE THREAD

**Issue by alfaruqrizqi18** [AndreHaueisen/flushbar#85]
I've build an flutter app. I use flush bar, when I run into lolipop ++ it works as well. But when I try to run into android kitkat it's not showing

> Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.348], locale en-ID)

> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Android Studio (version 3.5)
> [√] VS Code, 64-bit edition (version 1.38.0)
> [√] Connected device (1 available)

> • No issues found!

**Comment by AndreHaueisen** [comment]
Flutter has some limitations on Kitkat. I don't intend to debug it on versions below Lollipop since they belong in the past now (less than 7% use KitKat). Fell free to fork it and give it try if you really need it.
