### ISSUE TITLE
Styling the FlatButton

### ISSUE THREAD

**Issue by theweiweiway** [AndreHaueisen/flushbar#88]
Hi,

I'm trying to play with the styling of mainButton. Is there a way to wrap the FlatButton in a Padding, or ButtonTheme to get more fine grained control of the button styling? Currently, it doesn't work since mainButton only accepts FlatButton type.

Basically, i want to make the circle smaller and move it to the right a bit more:

![Screen Shot 2019-09-27 at 2 01 59 PM](https://user-images.githubusercontent.com/49566929/65791269-63778300-e12f-11e9-8d3e-5d38a84d2a2d.png)

Thanks

**Comment by AndreHaueisen** [comment]
Live in 1.10.4

**Comment by theweiweiway** [comment]
Thanks!
