### ISSUE TITLE
BoxShadow doesn't display

### ISSUE THREAD

**Issue by winqoo** [AndreHaueisen/flushbar#89]
I'm trying to add shadow to flushbar, but it doesn't display. I used the same code as in the readme example but still no result

` Flushbar(
      boxShadows: [
        BoxShadow(
            color: Colors.blue[800], offset: Offset(0.0, 2.0), blurRadius: 3.0)
      ],
      backgroundColor: Colors.white,
      messageText: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Text(
            "Out of stock"
            style: Theme.of(_context).textTheme.subtitle.copyWith(fontSize: 14),
          ),
          Icon(Icons.card_travel)
        ],
      ),
      duration: Duration(seconds: 2),
      flushbarPosition: FlushbarPosition.TOP,
    )..show(_context);`

**Comment by cfchris** [comment]
I'm having the same issue. I am using boxShadows property. And I just don't see them at all...

Code:
```
        Flushbar(
          // title, message, icon
          title: message['notification']['title'].toString(),
          message: message['notification']['body'].toString(),
          icon: Padding(
            padding: const EdgeInsets.only(left: 3.75),
            child: Icon(
              DpIcons.bell,
              size: 28.0,
              color: Colors.white,
            ),
          ),
          // config stuff
          backgroundColor: Theme.of(context).primaryColor,
          borderRadius: 4.0,
          boxShadows: [
            BoxShadow(
              blurRadius: 4.0,
              color: Colors.black54,
              spreadRadius: 2.0,
              offset: Offset(2.0, 2.0),
            ),
          ],
          dismissDirection: FlushbarDismissDirection.HORIZONTAL,
          flushbarPosition: FlushbarPosition.TOP,
          isDismissible: true,
          margin: EdgeInsets.all(6.0),
          shouldIconPulse: false,
        )..show(context);
```

Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by winqoo** [comment]
You have to downgrade flushbar to 1.8.2, there are some issues with constraints in the current version. Downgrading solved it for me

**Comment by cfchris** [comment]
@winqoo I think I'll just wait for a bit and hope for a new release. I'm also hoping that #87 is fixable and could be fixed in a new release.

**Comment by AndreHaueisen** [comment]
Live at  1.9.1
