### ISSUE TITLE
Remove "final" from the properties. (message ant title, at least)

### ISSUE THREAD

**Issue by renenucci** [AndreHaueisen/flushbar#94]
Would be nice if we have a possibility to override some parameters or configuration, eg.;

1 - Create a unique template notification object (flushbar) with all properties default seted.
2 - Replace text/title and some other properties according the type or subject of the notification.

Like this:

`var myTemplateNotification = getReferenceFromSomeWhere(AlertType.Warning); //Could be a clone object too`
`myTemplateNotification.message = 'lorem ipsum';'`
`myTemplateNotification.title = 'title';`

Even if I want to translate the message/title after the flushbar object was constructed, I can't.

I think that's would be very nice! Ty

**Comment by AndreHaueisen** [comment]
That is a bad idea. If you want a text, create a new Flushbar. It is meant to be immutable
