### ISSUE TITLE
Flushbar does not show on physical iOS device

### ISSUE THREAD

**Issue by jcairo** [AndreHaueisen/flushbar#95]
Flushbar shows as expected in the iOS simulator but does not show on a physical iOS device. No errors occur, flushbar simply doesn't appear.

I am receiving notifications from Google cloud messaging. I've created a service to deal specifically with these notifications.

Really pleased with this extension. Looks and functions perfectly on the simulator. Hoping there is a simple fix for this.

```dart
class CloudMessagingService {
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  BuildContext context;
  CloudMessagingService({this.context}) {
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) {
        Vibration.vibrate();
        Flushbar(
          flushbarStyle: FlushbarStyle.GROUNDED,
          icon: Icon(
            Icons.info_outline,
            color: Colors.yellow,
          ),
          titleText: Text(
            message['notification']['title'],
            style: kNotificationTitleText,
          ),
          messageText: Text(
            message['notification']['body'],
            style: kNotificationBodyText,
          ),

          backgroundColor: Colors.black,

      )..show(context);
```

The context is being passed in using a multiprovider that resides above the app scaffold

```dart
void main() => runApp(MaterialApp(
      home: MyApp(),
      title: 'Fight Bell',
      theme: kThemeData,
    ));

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<FirestoreService>.value(value: FirestoreService()),
        Provider<CloudMessagingService>.value(value: CloudMessagingService(context: context)),
        StreamProvider<FirebaseUser>.value(value: AuthService().user),
        Provider<AuthService>.value(value: AuthService()),
      ],

      child: Scaffold(...
```

**Comment by AndreHaueisen** [comment]
This has nothing to do with IOS. 
If your onMessage callback is indeed being called, the context you are passing has no navigator yet. You need to use that is generated after the first route is pushed (after "/" route is built).

**Comment by jcairo** [comment]
I can confirm the onMessage is called as expected.

I'm not explicitly using a navigator in this app. I'm using TabBar for page navigation.

I'm not sure how I can 'user what is generated after the first route is pushed'?

**Comment by AndreHaueisen** [comment]
Try using it with the context yield on your home screen.
The context inside MyApp's `build` method is not capable of pushing routes yet.

**Comment by jcairo** [comment]
Thanks for the help. That was exactly the issue.
